import React, { useState } from 'react';
import { Download } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { useReports } from '@/hooks/useReports';

const MONTHS = [
  'March 2024', 'February 2024', 'January 2024',
];

const ReportsPage: React.FC = () => {
  const { user } = useAuth();
  const [selectedMonth, setSelectedMonth] = useState(MONTHS[0]);
  const { data, loading } = useReports(selectedMonth);

  return (
    <div className="p-6 lg:p-8 bg-[#FAFAFA] min-h-screen">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6 max-w-[960px] mx-auto">
        <div>
          <h1 className="font-heading text-[24px] font-bold text-black">Reports</h1>
          <p className="font-body text-[14px] text-[#6B7280] mt-1">Generate and export administrative reports</p>
        </div>
        <div className="flex items-center gap-3">
          <select
            value={selectedMonth}
            onChange={e => setSelectedMonth(e.target.value)}
            className="px-3 h-[36px] rounded-[8px] border border-[#E5E7EB] bg-white text-black font-body text-[13px] focus:outline-none focus:border-[#de3163]"
          >
            {MONTHS.map(m => <option key={m}>{m}</option>)}
          </select>
          <button className="flex items-center gap-2 px-6 h-[36px] bg-[#de3163] text-white rounded-[8px] font-heading text-[13px] font-semibold transition-colors hover:bg-[#b32958] shadow-sm">
            <Download size={16} /> Export PDF
          </button>
        </div>
      </div>

      <div className="bg-white mx-auto max-w-[960px] shadow-sm relative pt-[2px]">
        <div className="absolute top-0 left-0 right-0 h-[2px] bg-[#de3163]" />

        <div className="p-[48px]">
          {/* Report Header */}
          <div className="mb-12">
            <h1 className="font-heading text-[22px] font-bold text-black leading-tight">New Heaven and New Earth</h1>
            <p className="font-body text-[13px] text-[#6B7280] mt-1">Sea of Glass Rustenburg — Administrative Report</p>
            <div className="flex items-center gap-4 mt-6">
              <p className="font-body text-[12px] text-[#6B7280]">Reporting Period: <strong className="font-medium text-black">{selectedMonth}</strong></p>
              <div className="w-1 h-1 rounded-full bg-[#E5E7EB]" />
              <p className="font-body text-[12px] text-[#6B7280]">Generated by: <strong className="font-medium text-black">{user?.name || 'Administrator'}</strong></p>
              <div className="w-1 h-1 rounded-full bg-[#E5E7EB]" />
              <p className="font-body text-[12px] text-[#6B7280]">Date: <strong className="font-medium text-black">{new Date().toLocaleDateString('en-GB')}</strong></p>
            </div>
          </div>

          {loading ? (
            <div className="text-center py-12 text-[#6B7280] font-body text-sm">Loading report data...</div>
          ) : (
            <>
              {/* Section 1: Attendance */}
              <section className="mb-10">
                <div className="border-t border-[#E5E7EB] pt-4 mb-6">
                  <h2 className="font-heading text-[14px] font-semibold text-black">1. Attendance Summary</h2>
                </div>
                <table className="w-full text-[13px] font-body">
                  <thead>
                    <tr className="border-b border-[#E5E7EB]">
                      <th className="text-left py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Department</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Total Members</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Physical Avg</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Online Avg</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Overall Att %</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">DB %</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(data?.byDepartment ?? []).map((row, idx) => (
                      <tr key={row.department} className={`border-b border-[#E5E7EB]/50 ${idx % 2 === 0 ? 'bg-white' : 'bg-[#FAFAFA]'}`}>
                        <td className="py-3 px-4 text-black">{row.label}</td>
                        <td className="text-right py-3 px-4 text-black">{row.memberCount}</td>
                        <td className="text-right py-3 px-4 text-black">{row.physicalAvg}</td>
                        <td className="text-right py-3 px-4 text-black">{row.onlineAvg}</td>
                        <td className="text-right py-3 px-4 text-black">{row.attendancePct}%</td>
                        <td className="text-right py-3 px-4 text-black">{row.dbPct}%</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="bg-black">
                      <td className="py-3 px-4 font-heading text-[13px] font-semibold text-white">Grand Total</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">{data?.grandTotal.members ?? 0}</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">{data?.grandTotal.physical ?? 0}</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">{data?.grandTotal.online ?? 0}</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">{data?.grandTotal.pct ?? 0}%</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">—</td>
                    </tr>
                  </tfoot>
                </table>
              </section>

              {/* Section 2: Evangelism */}
              <section className="mb-0">
                <div className="border-t border-[#E5E7EB] pt-4 mb-6">
                  <h2 className="font-heading text-[14px] font-semibold text-black">2. Evangelism Progress</h2>
                </div>
                <table className="w-full text-[13px] font-body">
                  <thead>
                    <tr className="border-b border-[#E5E7EB]">
                      <th className="text-left py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Stage</th>
                      <th className="text-right py-3 px-4 text-[#6B7280] font-heading text-[11px] font-normal uppercase tracking-[0.08em]">Count</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(data?.evangelismByStage ?? []).map((row, idx) => (
                      <tr key={row.stage} className={`border-b border-[#E5E7EB]/50 ${idx % 2 === 0 ? 'bg-white' : 'bg-[#FAFAFA]'}`}>
                        <td className="py-3 px-4 text-black">{row.label}</td>
                        <td className="text-right py-3 px-4 text-black">{row.count}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="bg-black">
                      <td className="py-3 px-4 font-heading text-[13px] font-semibold text-white">Pipeline Total</td>
                      <td className="text-right py-3 px-4 font-heading text-[13px] font-semibold text-white">{data?.evangelismTotal ?? 0}</td>
                    </tr>
                  </tfoot>
                </table>
              </section>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;
